# SynFinance Default Configuration
# Base configuration inherited by all environments

# Application Settings
app_name: "SynFinance"
version: "1.0.0"
debug: false

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 60
  reload: false
  log_level: "INFO"
  cors_origins:
    - "*"
  max_request_size: 10485760  # 10MB

# Database Configuration
database:
  host: "localhost"
  port: 5432
  name: "synfinance"
  user: "postgres"
  password: ""
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600
  echo: false
  ssl_mode: "prefer"
  retry_attempts: 3
  retry_delay: 1

# Cache Configuration
cache:
  enabled: true
  backend: "memory"
  host: "localhost"
  port: 6379
  db: 0
  password: null
  max_size: 10000
  ttl: 3600
  eviction_policy: "lru"

# Transaction Generation Configuration
generation:
  num_customers: 1000
  num_transactions: 10000
  fraud_rate: 0.02
  anomaly_rate: 0.05
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  seed: null
  parallel: true
  batch_size: 1000

# Machine Learning Configuration
ml:
  model_path: "models/"
  fraud_threshold: 0.5
  anomaly_threshold: 0.8
  batch_size: 100
  enable_gpu: false
  num_threads: 4
  cache_predictions: true
  model_refresh_interval: 3600
  feature_engineering:
    enabled: true
    fraud_features: true
    anomaly_features: true
    interaction_features: true
    total_features: 69

# Monitoring Configuration
monitoring:
  enabled: true
  prometheus_enabled: true
  prometheus_port: 9090
  grafana_enabled: true
  grafana_port: 3000
  export_interval: 60
  retention_days: 30
  alerting_enabled: true
  alert_webhook: null
  log_metrics: true
  metrics_file: "logs/metrics.log"

# Security Configuration
security:
  api_key_enabled: false
  api_keys: []
  jwt_enabled: false
  jwt_secret: ""
  jwt_algorithm: "HS256"
  jwt_expiry: 3600
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: 60
  cors_enabled: true
  allowed_hosts:
    - "*"
  ssl_enabled: false
  ssl_cert_path: null
  ssl_key_path: null
