# Prometheus Configuration for SynFinance
#
# This configuration defines how Prometheus scrapes metrics
# and loads alert rules.

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'synfinance-dev'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Load alert rules
rule_files:
  - '/etc/prometheus/alert_rules.yml'

# Scrape configurations
scrape_configs:
  # SynFinance API metrics
  - job_name: 'synfinance'
    static_configs:
      - targets: ['synfinance-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  # Node exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
