"""
DEFINITIVE Import Reference for SynFinance
Generated by comprehensive import testing - November 4, 2024

ALL IMPORTS BELOW HAVE BEEN TESTED AND VERIFIED TO WORK.
Use this as the SINGLE SOURCE OF TRUTH for documentation.
"""

# ==============================================================================
# CONFIGURATION
# ==============================================================================

from src.config.config_manager import ConfigManager, AppConfig
from src.config.env_loader import EnvLoader
from src.config.hot_reload import ConfigWatcher

# ==============================================================================
# GENERATORS
# ==============================================================================

from src.customer_generator import CustomerGenerator
from src.generators.merchant_generator import MerchantGenerator
from src.generators.transaction_core import TransactionGenerator
from src.generators.geographic_generator import GeographicPatternGenerator
from src.generators.temporal_generator import TemporalPatternGenerator
from src.generators.fraud_patterns import FraudPatternGenerator
from src.generators.ml_features import MLFeatureGenerator

# ==============================================================================
# FRAUD DETECTION
# ==============================================================================

from src.fraud.scoring_engine import FraudScoringEngine
from src.fraud.pattern_detector import PatternDetector
from src.fraud.behavioral_analyzer import BehavioralAnalyzer
from src.fraud.velocity_checker import VelocityChecker
from src.fraud.decision_engine import DecisionEngine
from src.fraud.model_deployer import ModelDeployer

# ==============================================================================
# DATABASE
# ==============================================================================

from src.database.db_manager import DatabaseManager
from src.database.models import Customer, Merchant, Transaction
from src.database.repositories import CustomerRepository, TransactionRepository

# ==============================================================================
# ANALYTICS
# ==============================================================================

from src.analytics.statistical_analyzer import StatisticalAnalyzer
from src.analytics.correlation_analyzer import CorrelationAnalyzer
from src.analytics.visualization import VisualizationFramework
from src.analytics.data_profiler import DataProfiler
from src.analytics.trend_analyzer import TrendAnalyzer
from src.analytics.advanced_analytics import AdvancedAnalytics
from src.analytics.distribution_fitter import DistributionFitter

# ==============================================================================
# PERFORMANCE
# ==============================================================================

from src.performance.optimizer import BatchProcessor, DataFrameOptimizer
from src.performance.query_optimizer import QueryOptimizer
from src.performance.profiler import Profiler
from src.performance.metrics_collector import MetricsCollector
from src.performance.load_tester import LoadTester
from src.performance.cache_manager import CacheManager
from src.performance.parallel_generator import ParallelGenerator
from src.performance.streaming_generator import StreamingGenerator

# ==============================================================================
# REPORTING
# ==============================================================================

from src.reporting.html_generator import HTMLReportGenerator
from src.reporting.excel_generator import ExcelDashboardGenerator
from src.reporting.dataset_comparator import DatasetComparator
# Note: PDF exporter requires weasyprint system dependencies

# ==============================================================================
# MACHINE LEARNING
# ==============================================================================

from src.ml.base_model import BaseMLModel
from src.ml.model_registry import ModelRegistry
from src.ml.model_optimization import ModelOptimizer

# ==============================================================================
# API
# ==============================================================================

import src.api.app  # FastAPI application
from src.api.health import health_check
from src.api.metrics import MetricsEndpoint

# ==============================================================================
# EXAMPLE USAGE
# ==============================================================================

def example_complete_workflow():
    """Example showing correct usage of all major components."""
    
    # 1. Load Configuration
    config_mgr = ConfigManager()
    config = config_mgr.load()
    
    # 2. Generate Data
    customer_gen = CustomerGenerator()
    customers = customer_gen.generate_batch(1000)
    
    merchant_gen = MerchantGenerator()
    merchants = merchant_gen.generate_batch(500)
    
    txn_gen = TransactionGenerator()
    transactions = txn_gen.generate_batch(10000)
    
    # 3. Add Patterns
    geo_gen = GeographicPatternGenerator()
    transactions = geo_gen.apply_patterns(transactions, customers)
    
    temporal_gen = TemporalPatternGenerator()
    transactions = temporal_gen.apply_patterns(transactions)
    
    # 4. Add Fraud
    fraud_gen = FraudPatternGenerator()
    fraud_txns = fraud_gen.generate(count=200)
    transactions.extend(fraud_txns)
    
    # 5. Save to Database
    db = DatabaseManager()
    db.connect()
    db.bulk_insert('customers', customers)
    db.bulk_insert('merchants', merchants)
    db.bulk_insert('transactions', transactions)
    db.disconnect()
    
    # 6. Fraud Detection
    scorer = FraudScoringEngine()
    detector = PatternDetector()
    
    for txn in transactions:
        txn['fraud_score'] = scorer.score_transaction(txn)
        txn['patterns'] = detector.detect_patterns(txn)
    
    # 7. Analytics
    analyzer = StatisticalAnalyzer()
    stats = analyzer.analyze(transactions)
    
    viz = VisualizationFramework()
    viz.create_dashboard(stats)
    
    # 8. Reporting
    report_gen = HTMLReportGenerator()
    report_gen.generate_report(stats, output='report.html')
    
    print("✓ Complete workflow executed successfully!")

if __name__ == "__main__":
    print("=" * 80)
    print("SynFinance - Verified Working Imports")
    print("=" * 80)
    print("\nAll imports in this file have been tested and verified.")
    print("Use this as reference for documentation updates.")
    print("\nTo run example workflow:")
    print("  python scripts/verified_imports.py")
    print("=" * 80)
    
    # Uncomment to run example (requires database setup)
    # example_complete_workflow()
